lsi: false
safe: true
source: ["./"]
include: ["dist", "dist/index.html", "dist/coi-serviceworker.js", "dist/assets", "dist/assets/**.js", "dist/assets/**.css", "dist/assets/**"]
exclude: ["README.md", "./README.md"]
incremental: false
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge