lsi: false
safe: true
source: ["./"]
include: ["./dist"]
exclude: ["./index.html"]
incremental: false
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge