name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main 

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        working-directory: ./web # Run in the 'web' subdirectory
        run: npm install

      - name: Build the project
        working-directory: ./web # Run in the 'web' subdirectory
        run: npm run build  # This will create web/dist
    
      - name: List contents of web/dist # <-- ADD THIS DIAGNOSTIC STEP
        run: ls -R ./web/dist

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: web/dist # Publish from the 'web/dist' directory